# Generated by Django 3.1.7 on 2021-03-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('founded', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(null=True)),
                ('date', models.DateField()),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brewer')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('ibu', models.IntegerField(null=True)),
                ('abv', models.FloatField(null=True)),
                ('brewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brewer')),
            ],
        ),
    ]
