# Generated by Django 3.1.7 on 2021-03-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210305_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discription',
            new_name='description',
        ),
    ]
